# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=256)),
                ('labels', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('chief', models.CharField(max_length=256)),
                ('image_path', models.CharField(max_length=256)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
